import Head from 'next/head'
import styles from '../styles/AppLayout.module.css'

export default function AppLayout({children}) {
    return(
        <div className={styles.mainLayout}>
            <Head>
                <title>Duckter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </div>
    )
}